[package]
name = "unfurl"
version = "0.1.0"
edition = "2021"

[dependencies]
url = "2.4.1"
clap = { version="3.1", features=["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
reqwest = { version = "0.11.22", features = ["blocking"] }

